-- Run this in the Supabase SQL editor, once, after scripts/schema-auth.sql.
-- This is a DESTRUCTIVE RESET, not a data-preserving migration: every row in
-- the tables below is wiped rather than mapped onto real accounts. That's a
-- deliberate choice (starting the first household fresh via normal sign-up
-- instead of migrating Cameron/Mallorie's existing swipes, favorites, decks,
-- meal plan, shopping list, imported recipes, and photos) — reconsider before
-- running this if that's not what you want anymore.
--
-- Because nothing is preserved, this does NOT need anyone to have signed in
-- first, and does NOT need your email addresses filled in anywhere — unlike
-- a real migration, there's no old text data to map onto new profile ids.
-- Sign-up and the first household are created entirely through the normal
-- app flow (SignInScreen -> HouseholdOnboardingScreen) after this runs.
--
-- Still recommended: export/back up the tables below first (Table Editor ->
-- export) in case "start fresh" turns out to mean "we wanted last week's
-- favorites back" — cheap insurance, not required.

-- ===========================================================================
-- STEP 0 -- sanity check: see what's about to be wiped and which check
-- constraints are about to be dropped, before doing either.
-- ===========================================================================
select 'recipe_priority' t, count(*) from recipe_priority
union all select 'swipe_events', count(*) from swipe_events
union all select 'swipe_decks', count(*) from swipe_decks
union all select 'recipe_photos', count(*) from recipe_photos
union all select 'imported_recipes', count(*) from imported_recipes
union all select 'meal_calendar_entries', count(*) from meal_calendar_entries
union all select 'recipe_tag_overrides', count(*) from recipe_tag_overrides
union all select 'recipe_overrides', count(*) from recipe_overrides
union all select 'meal_plan_items', count(*) from meal_plan_items
union all select 'shopping_list_items', count(*) from shopping_list_items;

select conrelid::regclass as table_name, conname, pg_get_constraintdef(oid) as definition
from pg_constraint
where contype = 'c' and pg_get_constraintdef(oid) ilike '%Cameron%';

-- ===========================================================================
-- STEP 1 -- wipe every table this touches. `swipe_decks cascade` also empties
-- swipe_deck_recipes and swipe_deck_shares (both FK to swipe_decks.id).
-- ===========================================================================
truncate table recipe_priority;
truncate table swipe_events;
truncate table swipe_decks cascade;
truncate table recipe_photos;
truncate table imported_recipes;
truncate table meal_calendar_entries;
truncate table recipe_tag_overrides;
truncate table recipe_overrides;
truncate table meal_plan_items;
truncate table shopping_list_items;

-- ===========================================================================
-- STEP 2 -- drop every check constraint that hardcodes 'Cameron'/'Mallorie',
-- wherever it actually lives (not by guessing autogenerated names). Has to
-- happen before the column type changes below.
-- ===========================================================================
do $$
declare c record;
begin
  for c in
    select conname, conrelid::regclass as tbl
    from pg_constraint
    where contype = 'c' and pg_get_constraintdef(oid) ilike '%Cameron%'
  loop
    execute format('alter table %s drop constraint %I', c.tbl, c.conname);
  end loop;
end $$;

-- ===========================================================================
-- STEP 3 -- recipe_priority / swipe_events (scripts/schema-priority-favorites.sql)
-- ===========================================================================
alter table recipe_priority
  add column household_id uuid not null references households (id),
  alter column user_id type uuid using (user_id::uuid),
  add constraint recipe_priority_user_id_fkey foreign key (user_id) references profiles (id);

alter table swipe_events
  add column household_id uuid not null references households (id),
  alter column user_id type uuid using (user_id::uuid),
  add constraint swipe_events_user_id_fkey foreign key (user_id) references profiles (id);

drop policy "anon full access" on recipe_priority;
drop policy "anon full access" on swipe_events;
create policy "household members" on recipe_priority for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());
create policy "household members" on swipe_events for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- apply_swipe's signature changes (p_user_id text -> uuid, new p_household_id).
drop function apply_swipe(text, text, text, text);
create or replace function apply_swipe(p_user_id uuid, p_recipe_id text, p_direction text, p_deck_id text, p_household_id uuid)
returns recipe_priority as $$
declare result recipe_priority;
begin
  insert into recipe_priority (user_id, recipe_id, household_id) values (p_user_id, p_recipe_id, p_household_id)
    on conflict (user_id, recipe_id) do nothing;

  if p_direction = 'right' then
    update recipe_priority set priority = priority + 1, favorited = true, updated_at = now()
      where user_id = p_user_id and recipe_id = p_recipe_id;
  elsif p_direction = 'left' then
    update recipe_priority set priority = priority - 1, updated_at = now()
      where user_id = p_user_id and recipe_id = p_recipe_id;
  else -- 'down'
    update recipe_priority set removed_at = now(), updated_at = now()
      where user_id = p_user_id and recipe_id = p_recipe_id;
  end if;

  update recipe_priority set removed_at = coalesce(removed_at, now())
    where user_id = p_user_id and recipe_id = p_recipe_id and priority <= 0;

  insert into swipe_events (user_id, recipe_id, direction, deck_id, household_id)
    values (p_user_id, p_recipe_id, p_direction, p_deck_id, p_household_id);

  select * into result from recipe_priority where user_id = p_user_id and recipe_id = p_recipe_id;
  return result;
end;
$$ language plpgsql;

grant execute on function apply_swipe(uuid, text, text, text, uuid) to authenticated;

-- ===========================================================================
-- STEP 4 -- swipe_decks / swipe_deck_recipes / swipe_deck_shares
-- (scripts/schema-swipe-decks.sql). Auto decks (source='auto', rebuilt
-- wholesale by build-swipe-decks.mjs from the shared recipe pool) stay
-- household_id NULL and readable by everyone -- they aren't household data.
-- Only manual decks are household-owned. swipe_deck_recipes/
-- swipe_deck_shares aren't given their own household_id column -- they're
-- scoped via a join back to swipe_decks, one source of truth for ownership.
-- ===========================================================================
alter table swipe_decks
  add column household_id uuid references households (id),
  add constraint swipe_decks_household_manual_check check (source = 'auto' or household_id is not null),
  alter column created_by drop not null,
  alter column created_by type uuid using (created_by::uuid),
  add constraint swipe_decks_created_by_fkey foreign key (created_by) references profiles (id);

alter table swipe_deck_shares
  alter column shared_with type uuid using (shared_with::uuid),
  alter column shared_by type uuid using (shared_by::uuid),
  add constraint swipe_deck_shares_shared_with_fkey foreign key (shared_with) references profiles (id),
  add constraint swipe_deck_shares_shared_by_fkey foreign key (shared_by) references profiles (id);

drop policy "anon full access" on swipe_decks;
drop policy "anon full access" on swipe_deck_recipes;
drop policy "anon full access" on swipe_deck_shares;

create policy "auto decks readable, manual decks household-owned" on swipe_decks for all to authenticated
  using (source = 'auto' or household_id = current_household_id())
  with check (source = 'auto' or household_id = current_household_id());

create policy "scoped via parent deck" on swipe_deck_recipes for all to authenticated
  using (exists (
    select 1 from swipe_decks d where d.id = deck_id
      and (d.source = 'auto' or d.household_id = current_household_id())
  ))
  with check (exists (
    select 1 from swipe_decks d where d.id = deck_id
      and (d.source = 'auto' or d.household_id = current_household_id())
  ));

create policy "scoped via parent deck" on swipe_deck_shares for all to authenticated
  using (exists (select 1 from swipe_decks d where d.id = deck_id and d.household_id = current_household_id()))
  with check (exists (select 1 from swipe_decks d where d.id = deck_id and d.household_id = current_household_id()));

-- scripts/build-swipe-decks.mjs runs as a batch script with the anon key and
-- no signed-in session (there's no service-role key in this project's
-- convention) -- it needs its own policy to keep rebuilding the global auto
-- decks, scoped strictly to source='auto' so it can never touch a
-- household's manual decks.
create policy "anon manages auto decks" on swipe_decks for all to anon
  using (source = 'auto') with check (source = 'auto');
create policy "anon manages auto deck recipes" on swipe_deck_recipes for all to anon
  using (exists (select 1 from swipe_decks d where d.id = deck_id and d.source = 'auto'))
  with check (exists (select 1 from swipe_decks d where d.id = deck_id and d.source = 'auto'));

-- ===========================================================================
-- STEP 5 -- recipe_photos (scripts/schema-recipe-photos.sql). Surrogate PK,
-- no widening needed.
-- ===========================================================================
alter table recipe_photos
  add column household_id uuid not null references households (id),
  alter column added_by type uuid using (added_by::uuid),
  add constraint recipe_photos_added_by_fkey foreign key (added_by) references profiles (id);

drop policy "anon full access" on recipe_photos;
create policy "household members" on recipe_photos for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- ===========================================================================
-- STEP 6 -- imported_recipes (scripts/schema-imported-recipes.sql). `id` is
-- generated as `imported-<random>` app-side, so cross-household collision
-- isn't a real risk -- PK stays `id`, no widening.
-- ===========================================================================
alter table imported_recipes
  add column household_id uuid not null references households (id),
  alter column added_by type uuid using (added_by::uuid),
  add constraint imported_recipes_added_by_fkey foreign key (added_by) references profiles (id);

drop policy "anon full access" on imported_recipes;
create policy "household members" on imported_recipes for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- ===========================================================================
-- STEP 7 -- meal_calendar_entries (scripts/schema-meal-calendar.sql). PK
-- MUST widen -- (entry_date, meal_type) alone would let two households
-- collide on the same calendar slot.
-- ===========================================================================
alter table meal_calendar_entries
  add column household_id uuid not null references households (id),
  alter column assigned_to type uuid using (assigned_to::uuid),
  add constraint meal_calendar_entries_assigned_to_fkey foreign key (assigned_to) references profiles (id);

alter table meal_calendar_entries drop constraint meal_calendar_entries_pkey;
alter table meal_calendar_entries add primary key (household_id, entry_date, meal_type);

drop policy "anon full access" on meal_calendar_entries;
create policy "household members" on meal_calendar_entries for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- ===========================================================================
-- STEP 8 -- recipe_tag_overrides (scripts/schema-recipe-tag-overrides.sql).
-- No identity column previously -- becoming household-scoped, see the note
-- at the top of this file. PK widens.
-- ===========================================================================
alter table recipe_tag_overrides add column household_id uuid not null references households (id);
alter table recipe_tag_overrides drop constraint recipe_tag_overrides_pkey;
alter table recipe_tag_overrides add primary key (household_id, recipe_id, category, tag_slug);

drop policy "anon full access" on recipe_tag_overrides;
create policy "household members" on recipe_tag_overrides for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- ===========================================================================
-- STEP 9 -- recipe_overrides (scripts/schema-recipe-overrides.sql). Same
-- household-scoping call as step 8. PK widens.
-- ===========================================================================
alter table recipe_overrides add column household_id uuid not null references households (id);
alter table recipe_overrides drop constraint recipe_overrides_pkey;
alter table recipe_overrides add primary key (household_id, recipe_id);

drop policy "anon full access" on recipe_overrides;
create policy "household members" on recipe_overrides for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- ===========================================================================
-- STEP 10 -- meal_plan_items (scripts/schema-meal-plan.sql). PK widens.
-- ===========================================================================
alter table meal_plan_items add column household_id uuid not null references households (id);
alter table meal_plan_items drop constraint meal_plan_items_pkey;
alter table meal_plan_items add primary key (household_id, recipe_id);

drop policy "anon full access" on meal_plan_items;
create policy "household members" on meal_plan_items for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- ===========================================================================
-- STEP 11 -- shopping_list_items (scripts/schema-shopping-list.sql). PK widens.
-- ===========================================================================
alter table shopping_list_items add column household_id uuid not null references households (id);
alter table shopping_list_items drop constraint shopping_list_items_pkey;
alter table shopping_list_items add primary key (household_id, item_key, unit_key);

drop policy "anon full access" on shopping_list_items;
create policy "household members" on shopping_list_items for all to authenticated
  using (household_id = current_household_id()) with check (household_id = current_household_id());

-- ===========================================================================
-- STEP 12 -- final check: every touched table should be empty, and none of
-- the ALTERs above should have errored out on a leftover row.
-- ===========================================================================
select 'recipe_priority' t, count(*) from recipe_priority
union all select 'swipe_events', count(*) from swipe_events
union all select 'swipe_decks', count(*) from swipe_decks
union all select 'recipe_photos', count(*) from recipe_photos
union all select 'imported_recipes', count(*) from imported_recipes
union all select 'meal_calendar_entries', count(*) from meal_calendar_entries
union all select 'recipe_tag_overrides', count(*) from recipe_tag_overrides
union all select 'recipe_overrides', count(*) from recipe_overrides
union all select 'meal_plan_items', count(*) from meal_plan_items
union all select 'shopping_list_items', count(*) from shopping_list_items;
